export const brand = {
  name: "YOUNG HUNG HDR STUDIO",
  shortName: "Young Hung HDR Studio",
  taglineZh: "以光為線索，走向更深的影像層次。",
  taglineEn: "Following light into deeper visual silence.",
  keywords: "HDR / Light / Travel / Silence / Nature / Storytelling",
};

export const navItems = [
  { href: "/", label: "Home", labelZh: "首頁" },
  { href: "/photography", label: "HDR Photography", labelZh: "HDR 攝影" },
  { href: "/films", label: "HDR Films", labelZh: "HDR 影像" },
  { href: "/journal", label: "Journal", labelZh: "札記" },
  { href: "/about", label: "About", labelZh: "關於" },
  { href: "/contact", label: "Contact", labelZh: "聯繫" },
];

export const copy = {
  hero: {
    eyebrow: "HDR Photography / HDR Films / HDR Travel Stories",
    title: "YOUNG HUNG HDR STUDIO",
    zh: "在超越 SDR 的光域之中，尋找風景的呼吸、旅途的靜默，以及影像尚未說出口的故事。",
    en: "Explore light beyond SDR. Where landscapes breathe, journeys fall quiet, and every frame holds a story before words arrive.",
    primary: "HDR Photography",
    primaryZh: "HDR 攝影",
    secondary: "HDR Films",
    secondaryZh: "HDR 影像",
    tertiary: "Journal",
    tertiaryZh: "札記",
  },
  home: {
    selectedTitle: "HDR PHOTOGRAPHY",
    selectedTitleZh: "精選 HDR 攝影",
    selectedSubtitle: "Exploring light beyond SDR.",
    selectedSubtitleZh: "在超越 SDR 的光域中，保留光的層次與沉默。",
    rangeTitle: "Beyond Standard Dynamic Range",
    rangeTitleZh: "超越標準動態範圍",
    rangeSubtitle: "HDR is not simply brighter. It preserves shadow, sky, metal, water, and remembered light within the same quiet frame.",
    rangeSubtitleZh: "HDR 不只是更亮的畫面，而是讓暗部、天空、金屬、水面與記憶中的光，同時被溫柔地保留下來。",
    pathsTitle: "Two Visual Paths",
    pathsTitleZh: "兩種影像路徑",
    pathsSubtitle: "Photography holds the weight of light. Film lets time continue moving through it.",
    pathsSubtitleZh: "靜態攝影凝住光的重量，動態影像延展時間的流動。",
  },
  portfolio: {
    title: "Portfolio",
    titleZh: "作品集",
    subtitle: "The portfolio follows two visual directions: HDR Photography and HDR Films.",
    subtitleZh: "影像依照媒介分為兩條主線：HDR Photography 與 HDR Films。",
    photography: {
      title: "HDR Photography",
      titleZh: "HDR 攝影",
      subtitle: "From mountains, coastlines, urban edges, and quiet moments in transit, each image preserves the atmosphere and layered light of the scene through an HDR imaging workflow.",
      subtitleZh: "從山脈、海岸、城市邊界到旅途中的片刻寧靜，以 HDR 工作流程保留現場光線的層次與空氣感。",
      cta: "Enter Photography",
      ctaZh: "進入 HDR 攝影",
    },
    films: {
      title: "HDR Films",
      titleZh: "HDR 影像",
      subtitle: "Moving images shaped by light in time, where highlights, shadows, and color move with a natural sense of presence.",
      subtitleZh: "以動態影像記錄光線在時間中的變化，讓高亮、陰影與色彩在畫面裡自然流動。",
      cta: "Enter Films",
      ctaZh: "進入 HDR 影像",
    },
  },
  photography: {
    title: "HDR Photography",
    titleZh: "HDR 攝影",
    subtitle: "Quiet landscapes, traces of travel, and places where light has stayed.",
    subtitleZh: "安靜的風景、遠行的痕跡，以及光停留過的地方。",
    intro: "My focus is not only clarity, but how light changes the emotional temperature of a place. HDR allows an image to move closer to the depth we sense on location, preserving detail without forcing highlights and shadows to compete.",
    introZh: "我關注的不只是畫面的清晰度，而是光線如何改變一個地方的情緒。HDR 讓影像能更接近人眼在現場感受到的深度，也讓自然中的細節不必在高光與陰影之間被犧牲。",
    gridTitle: "Frames of Light",
    gridTitleZh: "光的片段",
    gridSubtitle: "Each frame is a brief encounter with weather, terrain, and silence.",
    gridSubtitleZh: "每一張照片，都是一次與天氣、地形和沉默的短暫相遇。",
  },
  films: {
    title: "HDR Films",
    titleZh: "HDR 影像",
    subtitle: "Light is not only seen. It moves forward with time.",
    subtitleZh: "讓光不只被看見，也被時間帶著前進。",
    intro: "HDR film allows skies, reflections, night tones, and distant outlines to exist together within one frame. I want each film to feel like a quiet walk, without over-explaining, letting light and place unfold at their own pace.",
    introZh: "HDR 影像讓天空、反射、夜色與遠方的輪廓能在同一個畫面裡共存。我希望每支影片都像一段安靜的行走，沒有過度解釋，只讓光線和場景慢慢展開。",
    gridTitle: "Motion in High Dynamic Range",
    gridTitleZh: "高動態範圍中的時間",
    gridSubtitle: "Films crafted for YouTube HDR and modern high-luminance displays.",
    gridSubtitleZh: "為 YouTube HDR 與高亮度顯示設備優化的影像作品。",
  },
  journal: {
    title: "Journal",
    titleZh: "札記",
    subtitle: "Notes on travel, light, tools, and the imaging process.",
    subtitleZh: "關於路途、光線、器材與影像流程的短篇筆記。",
    intro: "Some images are made before the shutter is pressed. Others are completed through sorting, choosing, and waiting. This journal gathers the paths behind the work: arrival, observation, workflow, and the details outside the center of the frame.",
    introZh: "有些影像完成於按下快門之前，有些則完成於長時間的整理、選擇與等待。這裡收錄的是影像背後的路徑：抵達、觀察、工作流程，以及那些沒有出現在畫面中央的細節。",
    sectionTitle: "Field Notes",
    sectionTitleZh: "現場筆記",
  },
  about: {
    title: "About Young Hung",
    titleZh: "關於 Young Hung",
    subtitle: "HDR photographer and imaging workflow explorer, focused on nature, travel, and the layered language of light.",
    subtitleZh: "HDR 攝影師，影像工作流程研究者，長期關注自然、旅行與光的層次。",
    bodyZh: "Young Hung 以 HDR Photography、HDR Imaging Workflow、Travel Photography 與 Landscape Photography 為核心創作方向。Young Hung HDR Studio 是一個以個人視角建立的影像品牌。它不追求喧嘩，而是將鏡頭放在光落下的地方：山脈的邊緣、城市的反射、旅途中的停頓，以及自然中難以重複的片刻。",
    bodyEn: "Young Hung works across HDR Photography, HDR Imaging Workflow, Travel Photography, and Landscape Photography. Young Hung HDR Studio is a personal visual brand shaped by a quiet way of seeing. It places the lens where light arrives: along mountain edges, in urban reflections, within pauses during travel, and inside fleeting moments in nature.",
    philosophyTitle: "Visual Philosophy",
    philosophyTitleZh: "影像觀點",
    philosophyZh: "光線不是背景，而是主角。我相信一張好的 HDR 影像，應該讓技術退到安靜的位置，只留下更接近現場感受的深度。",
    philosophyEn: "Light is not the background. It is the subject. A strong HDR image lets technique step back, leaving only a deeper sense of being there.",
  },
  contact: {
    title: "Contact",
    titleZh: "聯繫",
    subtitle: "For collaborations, licensing, visual projects, and HDR workflow conversations.",
    subtitleZh: "合作、授權、影像製作與 HDR 工作流程交流，歡迎來信。",
    bodyZh: "如果你正在尋找具有自然感、旅途感與高動態範圍表現的影像，我很樂意聽聽你的計畫。",
    bodyEn: "If you are looking for imagery shaped by nature, travel, and high dynamic range, I would be glad to hear about your project.",
  },
  footer: {
    zh: "以 HDR 觀看光的深處。從自然、旅行與靜默之間，建立屬於影像的敘事。",
    en: "Seeing deeper into light through HDR. Building visual stories between nature, travel, and silence.",
  },
};
