export const brand = {
  name: "YOUNG HUNG HDR STUDIO",
  shortName: "Young Hung HDR Studio",
  taglineZh: "以光為線索，走向更深的影像層次。",
  taglineEn: "Following light into deeper visual silence.",
  keywords: "HDR / Light / Travel / Silence / Nature / Storytelling",
};

export const navItems = [
  { href: "/photography", label: "HDR Photography", labelZh: "HDR 攝影" },
  { href: "/films", label: "HDR Films", labelZh: "HDR 影片" },
  { href: "/tests", label: "Display Tests", labelZh: "顯示測試" },
  { href: "/about", label: "About", labelZh: "關於" },
  { href: "/contact", label: "Contact", labelZh: "聯繫" },
];

export const copy = {
  hero: {
    eyebrow: "HDR Photography / HDR Films / HDR Travel Stories",
    title: "Young Hung HDR Studio",
    zh: "在超越 SDR 的光域之中，尋找風景的呼吸、旅途的靜默，以及影像尚未說出口的故事。",
    en: "Explore light beyond SDR. Where landscapes breathe, journeys fall quiet, and every frame holds a story before words arrive.",
    primary: "HDR Photography",
    primaryZh: "HDR 攝影",
    secondary: "HDR Films",
    secondaryZh: "HDR 影像",
    tertiary: "Display Tests",
    tertiaryZh: "顯示測試",
  },
  home: {
    selectedTitle: "HDR PHOTOGRAPHY",
    selectedTitleZh: "精選 HDR 攝影",
    selectedSubtitle: "Exploring light beyond SDR.",
    selectedSubtitleZh: "在超越 SDR 的光域中，保留光的層次與沉默。",
    rangeTitle: "Beyond Standard Dynamic Range",
    rangeTitleZh: "超越標準動態範圍",
    rangeSubtitle: "HDR is not simply brighter. It preserves shadow, sky, metal, water, and remembered light within the same quiet frame.",
    rangeSubtitleZh: "HDR 不只是更亮的畫面，而是讓暗部、天空、金屬、水面與記憶中的光，同時被溫柔地保留下來。",
    pathsTitle: "Two Visual Paths",
    pathsTitleZh: "兩種影像路徑",
    pathsSubtitle: "Photography holds the weight of light. Film lets time continue moving through it.",
    pathsSubtitleZh: "靜態攝影凝住光的重量，動態影像延展時間的流動。",
  },
  portfolio: {
    title: "Portfolio",
    titleZh: "作品集",
    subtitle: "The portfolio follows two visual directions: HDR Photography and HDR Films.",
    subtitleZh: "影像依照媒介分為兩條主線：HDR Photography 與 HDR Films。",
    photography: {
      title: "HDR Photography",
      titleZh: "HDR 攝影",
      subtitle: "From mountains, coastlines, urban edges, and quiet moments in transit, each image preserves the atmosphere and layered light of the scene through an HDR imaging workflow.",
      subtitleZh: "從山脈、海岸、城市邊界到旅途中的片刻寧靜，以 HDR 工作流程保留現場光線的層次與空氣感。",
      cta: "Enter Photography",
      ctaZh: "進入 HDR 攝影",
    },
    films: {
      title: "HDR Films",
      titleZh: "HDR 影像",
      subtitle: "Moving images shaped by light in time, where highlights, shadows, and color move with a natural sense of presence.",
      subtitleZh: "以動態影像記錄光線在時間中的變化，讓高亮、陰影與色彩在畫面裡自然流動。",
      cta: "Enter Films",
      ctaZh: "進入 HDR 影像",
    },
  },
  photography: {
    title: "HDR Photography",
    titleZh: "HDR 攝影",
    subtitle: "Quiet landscapes, traces of travel, and places where light has stayed.",
    subtitleZh: "安靜的風景、遠行的痕跡，以及光停留過的地方。",
    intro: "My focus is not only clarity, but how light changes the emotional temperature of a place. HDR allows an image to move closer to the depth we sense on location, preserving detail without forcing highlights and shadows to compete.",
    introZh: "我關注的不只是畫面的清晰度，而是光線如何改變一個地方的情緒。HDR 讓影像能更接近人眼在現場感受到的深度，也讓自然中的細節不必在高光與陰影之間被犧牲。",
    gridTitle: "Frames of Light",
    gridTitleZh: "光的片段",
    gridSubtitle: "Each frame is a brief encounter with weather, terrain, and silence.",
    gridSubtitleZh: "每一張照片，都是一次與天氣、地形和沉默的短暫相遇。",
  },
  films: {
    title: "HDR Films",
    titleZh: "HDR 影像",
    subtitle: "Light is not only seen. It moves forward with time.",
    subtitleZh: "讓光不只被看見，也被時間帶著前進。",
    intro: "HDR film allows skies, reflections, night tones, and distant outlines to exist together within one frame. I want each film to feel like a quiet walk, without over-explaining, letting light and place unfold at their own pace.",
    introZh: "HDR 影像讓天空、反射、夜色與遠方的輪廓能在同一個畫面裡共存。我希望每支影片都像一段安靜的行走，沒有過度解釋，只讓光線和場景慢慢展開。",
    gridTitle: "Motion in High Dynamic Range",
    gridTitleZh: "高動態範圍中的時間",
    gridSubtitle: "Films crafted for YouTube HDR and modern high-luminance displays.",
    gridSubtitleZh: "為 YouTube HDR 與高亮度顯示設備優化的影像作品。",
  },
  tests: {
    title: "Display Level Test",
    titleZh: "顯示測試",
    subtitle: "Quick SDR and HDR viewing checks for shadow and highlight separation.",
    subtitleZh: "用來檢查 SDR / HDR 顯示器暗部與亮部層次的快速測試。",
    intro: "Start with SDR tests, then expand this page into additional HDR, grayscale, and tone-mapping checks as needed.",
    introZh: "先從顯示階調測試開始，之後可再擴充 HDR、灰階與 tone mapping 相關檢查。",
    sectionTitle: "Display Level Test",
    sectionTitleZh: "",
    sectionSubtitle: "Two basic ranges for checking near-black and near-white detail.",
    sectionSubtitleZh: "用兩個基礎範圍檢查接近黑位與白位的細節是否可辨識。",
    summaryTitle: "HDR Capability Summary",
    summaryTitleZh: "HDR 適性摘要",
    summarySubtitle: "Calculated from Peak Highlight, Near Black, and Near White results.",
    summarySubtitleZh: "依照峰值高光、Near Black 與 Near White 的測試結果計算。",
    summaryEmpty: "Complete the tests below to see your HDR capability summary.",
    summaryEmptyZh: "請先完成下方的測試，摘要會在這裡顯示。",
    overallScore: "Overall Score",
    overallScoreZh: "綜合分數",
    hdrGrade: "HDR Grade",
    hdrGradeZh: "HDR 等級",
    peakHighlight: "Peak Highlight",
    peakHighlightZh: "峰值高光",
    nearBlack: "Near Black",
    nearBlackZh: "Near Black",
    nearWhite: "Near White",
    nearWhiteZh: "Near White",
    detailScores: "Detail Scores",
    detailScoresZh: "細項分數",
    detailScoresDesc: "Scores are calculated from the values you selected above.",
    detailScoresDescZh: "分數依照你上方點選的數值計算。",
  },
  peakBrightness: {
    title: "Peak Brightness Test",
    titleZh: "峰值亮度測試",
    subtitle: "Estimate your display's peak highlight capability.",
    subtitleZh: "透過可辨識的 HDR 亮度階梯，估算顯示器的峰值高光能力。",
    intro: "This tool uses visible HDR brightness steps, not a colorimeter. Results are approximate and depend on your display, browser, and viewing environment.",
    introZh: "本工具依據肉眼可分辨的亮度階梯進行估算，並非色度計量測，結果會因顯示器、瀏覽器與觀看環境而異。",
    peakSectionTitle: "Peak Highlight",
    peakSectionTitleZh: "峰值高光",
    peakSectionSubtitle: "Select a small window size, then choose the brightest step you can still distinguish from the background.",
    peakSectionSubtitleZh: "選擇小視窗尺寸，點選最後仍能與背景清楚分辨的最亮階梯。",
    resultTitle: "Estimated Peak Highlight",
    resultTitleZh: "估算峰值高光",
    peakLabel: "Estimated Peak Highlight",
    peakLabelZh: "估算峰值高光",
    gradeLabel: "HDR Grade",
    gradeLabelZh: "HDR 等級",
    starsLabel: "Star Rating",
    starsLabelZh: "星等評分",
    windowSizeLabel: "Window Size",
    windowSizeLabelZh: "視窗尺寸",
    window1: "1% 視窗",
    window5: "5% 視窗",
    window10: "10% 視窗",
    window25: "25% 視窗",
    window100: "100% 全白",
    nitsLabel: "nits",
    fullscreen: "全螢幕測試",
    exitFullscreen: "離開全螢幕",
    fullscreenNote: "Window percentages are calibrated to the fullscreen test area.",
    fullscreenNoteZh: "視窗尺寸比例以全螢幕測試區域為準。",
    clipCheckLabel: "Clip detector",
    clipCheckLabelZh: "高光裁切偵測",
    clipCheckHint: "Adds a checker marker at a higher brightness. If the marker disappears, you've reached the display's highlight ceiling.",
    clipCheckHintZh: "在每格右下角加入更亮的棋盤標記；若標記消失，代表已達到顯示器的高光上限。",
    clipGuide: "Each square has a brighter checker marker in the bottom-right corner. The brightest step where the marker is still visible is your approximate peak.",
    clipGuideZh: "每個方塊右下角都有更亮的棋盤標記。標記仍然可見的最亮那一格，就是估算的峰值高光。",
    clipRangeHint: (selected: number, previous: number | null) =>
      previous
        ? `If the marker on ${selected} nits is gone, your peak is between ${previous} and ${selected} nits. If it is still visible, try the next brighter step.`
        : `If the marker on ${selected} nits is gone, your peak is below ${selected} nits. If it is still visible, try the next brighter step.`,
    clipRangeHintZh: (selected: number, previous: number | null) =>
      previous
        ? `若 ${selected} nits 的棋盤標記已消失，峰值介於 ${previous} 與 ${selected} nits 之間；若仍看得見，請試下一格更亮的階梯。`
        : `若 ${selected} nits 的棋盤標記已消失，峰值低於 ${selected} nits；若仍看得見，請試下一格更亮的階梯。`,
    note: "This is an estimation, not a calibrated measurement.",
    noteZh: "此為估算結果，並非經過校正的專業量測。",
    hdrModeSupported: "HDR output detected",
    hdrModeSupportedZh: "偵測到 HDR 輸出支援",
    hdrModeCssOnly: "HDR CSS supported",
    hdrModeCssOnlyZh: "瀏覽器支援 HDR CSS",
    hdrModeUnsupported: "Simulated mode",
    hdrModeUnsupportedZh: "模擬模式",
    hdrModeSupportedDesc: "Your browser and display report HDR support. Bright steps will attempt to render at real HDR luminance.",
    hdrModeSupportedDescZh: "瀏覽器與顯示器都回報支援 HDR，高亮度方塊會嘗試以真實 HDR 亮度呈現。",
    hdrModeCssOnlyDesc: "Your browser supports HDR CSS, but the OS/display is not in HDR mode. Enable system HDR to see real luminance.",
    hdrModeCssOnlyDescZh: "瀏覽器支援 HDR CSS，但作業系統或顯示器目前未處於 HDR 模式。開啟系統 HDR 才能看到真實亮度。",
    hdrModeUnsupportedDesc: "Your browser or display does not report HDR CSS support. Brightness steps are shown as a simulated gradient.",
    hdrModeUnsupportedDescZh: "瀏覽器或顯示器不支援 HDR CSS 輸出，亮度階梯以模擬漸層呈現。",
    hdrFallbackTitle: "Simulated HDR mode",
    hdrFallbackTitleZh: "HDR 模擬模式",
    hdrFallbackDesc: "Your browser or device does not support HDR WebGL output. Brightness steps are shown as an SDR gradient. For real HDR testing, use a desktop browser with an HDR display.",
    hdrFallbackDescZh: "你的瀏覽器或裝置不支援 HDR WebGL 輸出，亮度階梯以 SDR 漸層模擬。若要測試真實 HDR，請使用支援 HDR 的桌面瀏覽器與顯示器。",
    requiredLabel: "Required",
    requiredLabelZh: "必要",
    diagnosticsWebglHdr: "WebGL HDR output",
    diagnosticsWebglHdrZh: "WebGL HDR 輸出",
    diagnosticsRec2100Pq: "Rec.2100 PQ CSS",
    diagnosticsRec2100PqZh: "Rec.2100 PQ CSS",
    diagnosticsDynamicRange: "dynamic-range: high",
    diagnosticsDynamicRangeZh: "dynamic-range: high",
    diagnosticsVideoDynamicRange: "video-dynamic-range: high",
    diagnosticsVideoDynamicRangeZh: "video-dynamic-range: high",
    diagnosticsDisplayP3: "Display P3 CSS",
    diagnosticsDisplayP3Zh: "Display P3 CSS",
    diagnosticsColorGamutP3: "color-gamut: p3",
    diagnosticsColorGamutP3Zh: "color-gamut: p3",
    diagnosticsColorGamutRec2020: "color-gamut: rec2020",
    diagnosticsColorGamutRec2020Zh: "color-gamut: rec2020",
  },
  journal: {
    title: "Journal",
    titleZh: "札記",
    subtitle: "Collecting light along the road, tracing where each image begins.",
    subtitleZh: "在路上收藏光，在靜默裡書寫影像的來處。",
    intro: "Some frames come from the landscape itself. Others come from the road before arriving. These are not guides or gear reviews, but notes on how to see: how to wait for light while in motion, and how to remember the air and temperature of a moment long after leaving.",
    introZh: "有些畫面來自風景本身，有些來自抵達風景之前的路。這裡不是攻略，也不是器材評測，而是關於觀看的方式：如何在移動中等待光線，如何在離開之後，仍然記得某一片刻的空氣與溫度。",
    sectionTitle: "Field Notes",
    sectionTitleZh: "現場筆記",
  },
  about: {
    title: "About Young Hung",
    titleZh: "關於 Young Hung",
    subtitle: "HDR photographer and imaging workflow explorer, focused on nature, travel, and the layered language of light.",
    subtitleZh: "HDR 攝影師，影像工作流程研究者，長期關注自然、旅行與光的層次。",
    bodyZh: "Young Hung 以 HDR Photography、HDR Imaging Workflow、Travel Photography 與 Landscape Photography 為核心創作方向。Young Hung HDR Studio 是一個以個人視角建立的影像品牌。它不追求喧嘩，而是將鏡頭放在光落下的地方：山脈的邊緣、城市的反射、旅途中的停頓，以及自然中難以重複的片刻。",
    bodyEn: "Young Hung works across HDR Photography, HDR Imaging Workflow, Travel Photography, and Landscape Photography. Young Hung HDR Studio is a personal visual brand shaped by a quiet way of seeing. It places the lens where light arrives: along mountain edges, in urban reflections, within pauses during travel, and inside fleeting moments in nature.",
    philosophyTitle: "Visual Philosophy",
    philosophyTitleZh: "影像觀點",
    philosophyZh: "光線不是背景，而是主角。我相信一張好的 HDR 影像，應該讓技術退到安靜的位置，只留下更接近現場感受的深度。",
    philosophyEn: "Light is not the background. It is the subject. A strong HDR image lets technique step back, leaving only a deeper sense of being there.",
  },
  contact: {
    title: "Contact",
    titleZh: "聯繫",
    subtitle: "For collaborations, licensing, visual projects, and HDR workflow conversations.",
    subtitleZh: "合作、授權、影像製作與 HDR 工作流程交流，歡迎來信。",
    bodyZh: "如果你正在尋找具有自然感、旅途感與高動態範圍表現的影像，我很樂意聽聽你的計畫。",
    bodyEn: "If you are looking for imagery shaped by nature, travel, and high dynamic range, I would be glad to hear about your project.",
  },
  footer: {
    zh: "以 HDR 觀看光的深處。從自然、旅行與靜默之間，建立屬於影像的敘事。",
    en: "Seeing deeper into light through HDR. Building visual stories between nature, travel, and silence.",
  },
};
