import type { Metadata } from "next";
import { guideMetadata } from "@/lib/travel-guide-seo";
import "../guide-pages.css";
import "../field-notes.css";
import "../field-notes-footer.css";
import "../cta.css";
import "../cta-4k.css";
import "../video-overrides.css";
import "../photo-inserts.css";
import "./etosha-map.css";

export const metadata: Metadata = guideMetadata({ title: "納米比亞攝影攻略｜Etosha Safari、600mm 與 8K HDR", description: "納米比亞野生動物與星空攝影實戰：Etosha Safari、600mm 長焦、夜拍、風沙防護與 8K HDR 備份。", path: "/travel/guide/photography/" });
const BASE_PATH = process.env.NEXT_PUBLIC_BASE_PATH || "";

export default function PhotographyPage(){return <main className="field-page">
  <nav className="field-nav"><a href={`${BASE_PATH}/travel/guide/`}>← RETURN TO GUIDE</a><span>07 / PHOTOGRAPHY</span></nav>
  <section className="field-hero photography-hero"><p>FIELD NOTES / 07</p><h1><i>荒野很大，</i><i>鏡頭還要更長。</i></h1><div><span>WILDLIFE · NIGHT · TIMELAPSE</span><span>NAMIBIA · 2025</span></div></section>
  <section className="field-intro field-intro-story"><span>KENYA CLOSE / ETOSHA WAITS</span><p><strong>肯亞容易爆框，Etosha 你只能等。</strong></p><p>肯亞的 Safari，獅子會填滿你的觀景窗，長頸鹿從車旁低頭走過；長焦鏡頭有時反而太遠。Etosha 的規則不同。</p><p>車輛必須留在指定道路與觀景區，不能為了一隻遠方的獅子駛進荒野。動物從哪個方向出現、離道路有多遠，都不是攝影者能決定的事。</p><p>你能做的，只有開到水塘邊，關掉引擎，然後等。有時候動物會走近。有時候等了一個下午，水塘還是空的。</p><p>這種不確定性，或許正是 Etosha 最誠實的地方：它不是一座戶外動物園，而是一片真正屬於動物的荒野，人類只是被允許在邊緣旁觀。</p></section>
  <section className="field-section field-light field-video-note"><span>FIELD NOTE / 600MM</span><header><div></div><h2><i>不是追求更大的數字，</i><i>而是把真實距離還原。</i></h2></header><div className="field-copy"><p>在 Etosha，動物與道路之間的距離，不是攝影者能縮短的。這支短片，讓你直接看見為什麼——600mm，有時只是把那段距離忠實地還原進畫面。</p></div><div className="guide-video-embed"><iframe src="https://www.youtube-nocookie.com/embed/KW6eC-4mFtw?rel=0&modestbranding=1" title="Why a 600mm lens helps with wildlife photography" loading="lazy" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowFullScreen /></div><p className="field-video-caption">影片示範：600mm 如何保留野生動物與車輛之間的距離。</p></section>
  <section className="field-section"><span>01 / WILDLIFE</span><header><div></div><h2><i>600mm，</i><i>只是拍得到的開始。</i></h2></header><div className="field-grid"><article><b>DISTANCE</b><h3>道路決定了拍攝距離</h3><p>Etosha 不允許車輛離開指定道路尋找動物，遊客也不能在非指定區域下車。動物若停在鹽田或水塘另一側，再專業的嚮導也只能尋找較好的道路位置，因此等效 600mm 以上會比一般旅遊長焦更實用。</p></article><article><b>ANGLE</b><h3>拍得到，不代表能到水平視角</h3><p>坐在 Safari 車上通常高於動物眼睛，鏡頭容易形成向下俯拍。無法下車改變高度時，只能利用較低的車窗、遠一點的拍攝距離、地形高低差，或等待動物走到更合適的位置。</p></article><article><b>AIR</b><h3>超長焦最怕的，不單單是手震</h3><p>焦段愈長、距離愈遠，熱浪、浮塵與空氣擾動就愈容易吃掉細節。即使對焦準確、快門夠快，影像仍可能像隔著一層水。清晨、較短的拍攝距離與避免橫跨受熱地面，往往比再加增距鏡有效。</p></article><article><b>SUPPORT</b><h3>Safari 車上，豆袋比腳架實用</h3><p>無論白天或夜間，豆袋都可以放在窗框、車門邊緣或開啟的車頂旁，穩定長鏡頭並減輕手持負擔；發現動物或車輛重新移動時，也能迅速改變拍攝方向。</p></article></div><blockquote className="field-quote">焦段只解決畫面大小。<br />距離、角度與空氣，才決定最後剩下多少細節。</blockquote></section>
  <section className="field-section field-light"><span>02 / FINDING WILDLIFE</span><header><div></div><h2><i>看見什麼，</i><i>有時候真的需要運氣。</i></h2></header><div className="field-grid"><article><b>GUIDE</b><h3>不要只問在哪裡，也要問牠要去哪裡</h3><p>出發前先讓嚮導知道目標物種、照片或影片需求，以及願意等待多久。發現動物後，也可以請嚮導依足跡、視線、風向、水源與習性，預測牠下一步可能怎麼移動。比起不斷換水塘，有時留在原地的耐心，才等得到真正的行為。</p></article><article><b>NO GREAT MIGRATION</b><h3>這裡沒有東非式的大遷徙</h3><p>Etosha 的動物會隨降雨、水源與食物在園區內移動，但不是肯亞、坦尚尼亞那種成群跨越草原與河流的大遷徙。拍攝重點更像是在廣大的園區裡，等待動物走向水塘，或由嚮導判斷牠們可能出現的區域。</p></article><article><b>TIME OF DAY</b><h3>白天看見的，可能只是休息</h3><p>許多掠食動物在清晨、傍晚與夜間較活躍，日間炎熱時常躲在樹蔭或灌木下休息。白天不是完全看不到，但要拍到移動、互動甚至獵食，通常更依賴出發時間、耐心與運氣。</p></article><article><b>NAMIBIA PRIVATE RESERVES</b><h3>大型 Lodge 的私人保護區，不一定輸國家公園</h3><p>納米比亞部分大型 Lodge 擁有或合作經營私人保護區，棲地、物種與活動安排和 Etosha 不完全相同。專屬嚮導、較少車流、夜間活動與不同的觀察路線，可能帶來不輸國家公園的體驗；有時甚至不必坐上 Safari 車，動物就可能出現在 Lodge 周圍。</p></article><article><b>BINOCULARS</b><h3>望遠鏡不是配件，而是必備</h3><p>Etosha 地勢開闊，動物經常離道路很遠。望遠鏡能先確認遠方是石頭、樹影還是真正的動物，也能在超長焦架好以前觀察移動方向。受限於道路與距離，它在這裡不是偶爾拿出來看的配件，而是每天尋找動物的工具。</p></article><article><b>PATIENCE</b><h3>先觀察，再決定要不要離開</h3><p>動物短暫抬頭、改變耳朵方向或突然集體警戒，都可能是下一段行為的前兆。嚮導的判讀加上旅客願意等待，往往比單純增加行車里程，更有機會換到一張有故事的照片。</p></article></div></section>
  <section className="field-section"><span>03 / DAYS &amp; SEASONS</span><header><div></div><h2><i>在 Etosha，</i><i>天數與季節決定相遇的方式。</i></h2></header><div className="field-copy"><p>Etosha 面積約 22,935 平方公里，接近台灣面積的三分之二。</p><p>動物不會按照行程表出現。只安排一天，可能正好遇見獅群，也可能花了大半天，只看見遠方的一個身影。增加天數不是保證，而是讓不同水塘、不同時段與不同區域，多幾次相遇的機會。</p><p><strong>住在哪裡，也決定能不能趕上黃金時間。</strong></p><p>如果住在國家公園外，清晨需要等待入口開放、完成入園手續，再從大門開往水塘；傍晚也必須預留回到出口的時間。真正抵達動物身邊時，日出後最柔和的光線可能已經過去，日落前也不能無限制停留。</p><p>住在園內仍不代表可以任意夜間行車，但比較容易參加園方安排的清晨、傍晚與夜間 Game Drive，也能利用營區的照明水塘繼續觀察。對以野生動物攝影為主要目的的旅程來說，園內住宿不是單純省車程，而是在購買最難取代的光線與時間。</p><p><strong>乾季與雨季，不是好壞的差別。</strong></p><p>乾季時自然水源減少，動物較容易聚集在固定水塘，尋找大型哺乳動物的機會相對穩定，也是多數旅客選擇 Safari 季節的重要原因。</p><p>雨季過後，地景逐漸轉綠，動物分散在更廣大的園區裡，尋找難度也隨之提高。但這個季節可能帶來候鳥、新生幼獸，以及完全不同於乾季的色彩與生命感。</p><p>季節決定的不是「有沒有動物」，而是你要用什麼方式等待牠們，以及最後帶走什麼樣的畫面。</p></div><blockquote className="field-quote">專業嚮導能提高機會，天數能增加嘗試。<br />但荒野始終不承諾，今天一定會讓你看見什麼。</blockquote></section>
  <section className="field-section field-light"><span>04 / FIELD RULES</span><header><div></div><h2><i>有些畫面，</i><i>不值得用冒險換來。</i></h2></header><div className="field-grid"><article><b>SHUTTER</b><h3>先把動作凝結，再追求低 ISO</h3><p>野生動物不會配合重拍。奔跑、甩頭、拍翅與車身震動都需要更高快門；寧可接受較高 ISO，也不要讓關鍵動作因快門不足而模糊。實際速度仍應依物種、焦段與動作強度調整。</p></article><article><b>STAY IN THE VEHICLE</b><h3>不能下車，就不要為角度冒險</h3><p>園區內必須留在指定道路，非指定地點也不能離開車輛。能下車活動與整理器材的地方，主要是營區和指定區域；任何照片都不值得為了降低視角、靠近動物或撿拾器材而違反規定。</p></article><article><b>DRONE</b><h3>空拍限制嚴格，不要臨時嘗試</h3><p>外國旅客使用無人機須事先向納米比亞民航主管機關申請；國家公園內沒有正式許可不得飛行，攜帶入園也應申報。不要因為周圍無人就試飛，私人土地同樣還要取得地主同意並符合航空規定。</p></article><article><b>WILDLIFE FIRST</b><h3>安全不只保護旅客，也保護動物</h3><p>不要求嚮導逼近、阻擋去路或長時間追逐；動物出現警戒、護幼或改變行為時，就應拉開距離。拍攝的界線，不是器材還能不能拍，而是現場是否仍對人與動物安全。</p></article></div></section>
  <section className="field-section"><span>05 / SOUTHERN SKY</span><header><div></div><h2><i>國際暗空保護區，</i><i>也抵擋不了滿月。</i></h2></header><div className="field-grid"><article><b>DARKNESS</b><h3>低光害，不等於每晚都適合拍銀河</h3><p>納米比亞偏遠沙漠遠離城市燈光，其中 NamibRand 更是正式認證的國際暗空保護區。但天空再暗，滿月仍會壓低銀河與暗星雲的對比；若銀河核心是主要目標，月相和月出、月落時間必須和住宿日期一起規劃。</p></article><article><b>SEASON</b><h3>月份相近，季節卻與台灣相反</h3><p>銀河核心常見的拍攝期大致仍落在每年二、三月至十月前後，並不是把台灣月份整個顛倒；真正相反的是季節。台灣進入春夏時，納米比亞正走向秋冬，夜晚更冷，銀河的方向、仰角與構圖也完全不同。</p></article><article><b>NO POLARIS</b><h3>南方天空沒有北極星</h3><p>在納米比亞看不到北極星，南天極附近也沒有同樣明亮、可直接辨認的極星。拍攝星軌或使用赤道儀時，不能沿用北半球的找星方式，需要利用南十字星、指極星或星圖程式判斷南天極。</p></article><article><b>SOUTHERN OBJECTS</b><h3>抬頭會遇見另一套星空</h3><p>南十字星、煤袋暗星雲、船底座星雲，以及大小麥哲倫雲，都是南半球代表性的深空與銀河目標。它們不只是辨認方向的工具，也能成為縮時、星野與沙漠前景構圖的主角。</p></article><article><b>SPITZKOPPE ARCH</b><h3>石拱門，是銀河最自然的畫框</h3><p>Spitzkoppe 的天然石拱門位在花崗岩地形之中，銀河升起時可以把拱門、岩壁與人物一起放進構圖。拍攝前應先在白天確認銀河方向、取景位置與回程路線，不要等到全黑後才第一次找角度。</p></article><article><b>HIKING SAFETY</b><h3>主要風險不是猛獸，而是腳下</h3><p>我們前往的石拱門拍攝區並不是以兇猛大型野生動物出沒為主要風險；步行與攀爬本身也不算困難。但入夜後的花崗岩高低差、鬆動石塊、強風與器材重量仍會增加失足機會。頭燈與備用照明不可少，移動時先收好相機、空出雙手，也不要脫離嚮導或忽略蛇、蠍等小型生物。</p></article></div><blockquote className="field-quote">低光害決定天空有多深。<br />月相、季節與方向，才決定那一晚能拍到什麼。</blockquote></section>
  <section className="field-section field-light"><span>06 / WIND</span><header><div></div><h2><i>星空很安靜，</i><i>夜裡的風卻不是。</i></h2></header><div className="field-grid"><article><b>TRIPOD</b><h3>腳架可能真的會倒</h3><p>沙漠與岩地入夜後風勢可能突然增強。縮時攝影不能只把腳架展開就離開；應壓低腳架高度、縮短中柱，並確認吊掛配重不會反而被風吹得擺動。</p></article><article><b>TIMELAPSE</b><h3>先顧穩定，再決定拍多久</h3><p>長時間序列最怕中途位移。除了構圖與間隔，也要預留防風位置、電池續航、露水與沙塵防護；必要時寧可縮短拍攝，也不要讓整套器材獨自留在強風裡。</p></article></div></section>
  <section className="field-section"><span>07 / TWO BODIES</span><header><div></div><h2><i>一台留給遠方，</i><i>一台等牠靠近。</i></h2></header><div className="field-grid"><article><b>LONG</b><h3>一台留給超長焦</h3><p>遠方動物需要 600mm 以上，但牠可能突然走近車旁。若只有一台機身，臨時拆換鏡頭不只會錯過瞬間，也會讓沙塵進入接環與機身。</p></article><article><b>WIDE</b><h3>另一台保留環境與近距離</h3><p>第二台機身可搭配中長焦或標準變焦。當大象靠近、長頸鹿穿越道路，或需要連同車輛與地景一起拍攝時，可以立刻切換，避免超長焦只剩局部、整隻動物塞不進畫面。</p></article></div></section>
  <section className="field-section field-light"><span>08 / COAST &amp; DUST</span><header><div></div><h2><i>防塵防滴，</i><i>不等於不怕風沙。</i></h2></header><div className="field-grid"><article><b>COAST</b><h3>海岸動物還有鹽霧與濕氣</h3><p>拍攝海豹、鳥類與海岸景觀時，器材面對的不只是沙，也有鹽霧、濕氣與冷風。離開海岸後應先擦拭外部，避免鹽分長時間留在機身、鏡筒與腳架關節。</p></article><article><b>DESERT</b><h3>沒有換鏡，細沙還是進得去</h3><p>細沙會附著在變焦環、對焦環、按鍵、鏡筒接縫與腳架鎖點；反覆操作時，沙粒可能被帶進活動結構。</p><p>防塵防滴的旗艦機身與內變焦鏡頭也不是完全密封。風沙增強時，停止換鏡、減少操作轉環、加上防護套；必要時直接把器材收回密封袋或車內。</p></article></div><blockquote className="field-quote">器材的防護規格，是多一層緩衝。<br />不是允許它留在風沙裡繼續工作的保證。</blockquote></section>
  <section className="field-section"><span>09 / DATA</span><header><div></div><h2><i>8K HDR 的重量，</i><i>回到房間才開始。</i></h2></header><div className="field-copy"><p>高解析影片、長時間縮時與連拍野生動物，會快速吃掉記憶卡與硬碟空間。偏遠 Lodge 的網路不足以依靠雲端備份，因此每天回房後應完成至少兩份實體備份，並把儲存裝置分開保管。</p><p>真正需要帶多少電池、記憶卡與 SSD，最後應以每天的 8K HDR 拍攝量反推，而不是只看旅程天數。清潔器材也應回到無風、較乾淨的室內再做，不要在沙塵仍飄動時打開機身接環。</p></div><blockquote className="field-quote">器材不是帶得越多越好。<br />而是每一件，都必須能在風、沙與長途移動裡真正被使用。</blockquote></section>
<section className="field-section field-light"><span>09 / NIGHT LIGHT</span><header><div></div><h2><i>夜拍需要紅光，</i><i>移動才需要白光。</i></h2></header><div className="field-grid"><article><b>RED LIGHT</b><h3>讓眼睛與畫面都留在黑暗裡</h3><p>拍星空、縮時或等待夜行性動物時，使用可調低亮度的紅光頭燈。它能維持暗適應，也降低對同伴構圖、長曝與野生動物的干擾；開燈前先確認光束不會直射鏡頭或動物。</p></article><article><b>WHITE LIGHT</b><h3>只在走路與安全需要時使用</h3><p>參加 Lodge 安排的夜間 Safari 或夜間觀察時，白光模式以<strong>走路、上下車與緊急安全</strong>為主。不要自行用強光追照動物；何時照明、照向哪裡，跟著嚮導與保護區規定即可。</p></article></div></section>
  <section className="photo-insert"><span>FIELD DETAIL / SPITZKOPPE</span><h2>拱門不是抵達的終點，<br />而是離開前要再回頭看一次的地方。</h2><p>進入拱門拍攝前，先確認從哪裡進、從哪裡出。日落後岩石的方向感會快速消失，頭燈、備用照明與回程路線都應在天黑前確認。</p><figure><img src={`${BASE_PATH}/travel/spitzkoppe-arch.avif`} alt="Spitzkoppe 岩石拱門與夕陽"/><figcaption>先記住入口與出口，再把注意力交給光線。</figcaption></figure></section>
  <nav className="guide-related-links" aria-label="相關旅行攻略"><span>READ NEXT</span><a href={`${BASE_PATH}/travel/guide/transport/`}>移動與住宿</a><a href={`${BASE_PATH}/travel/guide/practical/`}>氣候、網路與途中日常</a></nav>
  <a className="guide-next-cta" href={`${BASE_PATH}/travel/guide/money-shopping/`}>下一步：安排換錢與伴手禮 →</a>
  <footer className="field-footer"><a href={`${BASE_PATH}/travel/guide/`}>回到準備旅行 ↗</a><span>YOUNG HUNG HDR STUDIO</span></footer>
</main>}
